import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Open_Sans } from 'next/font/google'

const openSans = Open_Sans({
  subsets: ["latin"],
})

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Blog AI App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html className = {openSans.className} lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
